CREATE TABLE DEPT_COPY AS SELECT *FROM DEPT;
CREATE TABLE EMP_COPY AS SELECT *FROM EMP;

CREATE VIEW EMP_VIEW30 AS SELECT EMPNO, ENAME, DEPTNO FROM EMP_COPY WHERE DEPTNO = 30;

SELECT *FROM EMP_VIEW30;

CREATE VIEW EMP_VIEW20 AS SELECT EMPNO, ENAME, DEPTNO, MGR FROM EMP_COPY WHERE DEPTNO = 20;

SELECT *FROM EMP_VIEW20;

SELECT VIEW_NAME, TEXT FROM USER_VIEWS;

INSERT INTO EMP_VIEW30 VALUES(1111, 'AAAA', 30);

SELECT *FROM EMP_COPY;

INSERT INTO EMP_VIEW30 VALUES(8000, '김천사', 30);

SELECT *FROM EMP_COPY;

CREATE OR REPLACE VIEW EMP_VIEW(사원번호, 사원명, 급여, 부서번호) AS SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP_COPY;

SELECT *FROM EMP_VIEW WHERE 부서번호 = 30;

CREATE VIEW SAL_VIEW AS SELECT D.DNAME, MAX(E.SAL) AS MAX_SAL, MIN(E.SAL) AS MIN_SAL FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO GROUP BY D.DNAME;

SELECT *FROM SAL_VIEW;

SELECT ROWID, ROWNUM, EMPNO, ENAME, HIREDATE FROM EMP ORDER BY HIREDATE ASC;

CREATE  VIEW VIEW_HIRE AS SELECT EMPNO, ENAME, HIREDATE FROM EMP ORDER BY HIREDATE ASC;

SELECT ROWNUM, EMPNO, ENAME, HIREDATE FROM VIEW_HIRE WHERE ROWNUM <= 5;

SELECT ROWNUM EMPNO, ENAME, HIREDATE FROM(SELECT EMPNO, ENAME, HIREDATE FROM EMP ORDER BY HIREDATE ASC) WHERE ROWNUM <= 5;

SELECT ROWNUM AS RANKING, EMPNO, ENAME, SAL FROM(SELECT EMPNO, ENAME, SAL FROM EMP ORDER BY SAL DESC) WHERE ROWNUM <= 3;

