SELECT INDEX_NAME, TABLE_NAME, COLUMN_NAME FROM USER_IND_COLUMNS WHERE TABLE_NAME IN ('EMP', 'DEPT');

DROP TABLE EMP01;
CREATE TABLE EMP01 AS SELECT *FROM EMP;

SELECT TABLE_NAME, INDEX_NAME, COLUMN_NAME FROM USER_IND_COLUMNS WHERE TABLE_NAME IN('EMP', 'EMP01');

INSERT INTO EMP01 SELECT *FROM EMP01;

SELECT COUNT(*) FROM EMP01;

INSERT INTO EMP01(EMPNO, ENAME) VALUES(1111,'ȫ�浿');

SELECT DISTINCT EMPNO, ENAME FROM EMP01 WHERE ENAME = 'ȫ�浿';

CREATE INDEX IDX_EMP01_ENAME ON EMP01(ENAME);