DROP TABLE DEPT01;
CREATE TABLE DEPT01 AS SELECT *FROM DEPT WHERE 1 = 0;
DESC DEPT01;

INSERT INTO DEPT01(DEPTNO, DNAME, LOC) VALUES(10, '영업부', '부산');

SELECT *FROM DEPT01;

DROP TABLE SAM01;
CREATE TABLE SAM01(EMPNO NUMBER(4),
                   ENAME VARCHAR2(10),
                   JOB VARCHAR2(9),
                   SAL NUMBER(7,2));
                   
INSERT INTO SAM01 VALUES(1000, '사과', '경찰', 1000);
INSERT INTO SAM01 VALUES(1010, '바나나', '간호사', 1500);
INSERT INTO SAM01 VALUES(1020, '오렌지', '의사', 2000);

SELECT *FROM SAM01;

INSERT INTO SAM01 VALUES(1030, '베리', NULL, 2500);
INSERT INTO SAM01 VALUES(1040, '망고', '', 25000);

DROP TABLE DEPT02;

CREATE TABLE DEPT02 AS SELECT *FROM DEPT WHERE 1 = 0;

INSERT INTO DEPT02 SELECT *FROM DEPT;

SELECT *FROM DEPT02;

INSERT INTO SAM01 SELECT EMPNO, ENAME, JOB, SAL FROM EMP WHERE DEPTNO = 10;

DROP TABLE EMP01;

CREATE TABLE EMP01 AS SELECT *FROM EMP;

SELECT *FROM EMP01;

UPDATE EMP01 SET DEPTNO = 30 WHERE DEPTNO = 10;

UPDATE EMP01 SET SAL = SAL * 1.1 WHERE SAL >= 400;

UPDATE SAM01 SET SAL = SAL - 5000 WHERE SAL >= 10000;

CREATE TABLE SAM02(ENAME VARCHAR2(10),
                   SAL NUMBER(7,2),
                   HIREDATE DATE,
                   DEPTNO NUMBER(2));
                   
INSERT INTO SAM02 SELECT ENAME, SAL, HIREDATE, DEPTNO FROM EMP;  

SELECT *FROM SAM02;

UPDATE SAM02 SET SAL = SAL + 100 WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE LOC = '인천');

DELETE FROM SAM01 WHERE JOB IS NULL;

SELECT *FROM SAM02;

DELETE FROM SAM02 WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME = '영업부');