DROP TABLE DEPT01;

CREATE TABLE DEPT01 AS SELECT *FROM DEPT;

SELECT *FROM DEPT01;

DELETE FROM DEPT01 WHERE DEPTNO = 40;
COMMIT;

DELETE FROM DEPT01 WHERE DEPTNO = 30;
SAVEPOINT C1;

DELETE FROM DEPT01 WHERE DEPTNO = 20;
SAVEPOINT C2;

DELETE FROM DEPT01 WHERE DEPTNO = 10;

ROLLBACK;
